piVersion: mlpie.ai/v1
kind: Environment
metadata:
  name: "dev-environment-01"
  description: "Primary development environment with multiple data sources."
  labels:
    - "dev"
    - "data-intensive"
spec:
  projectRef:
    name: "sample-ml-project"

  repositories:
    - name: "datasets"
      url: "https://github.com/mlpie-hq/tests"
      auth:
        type: "token"
        secret_ref: "test-repo-token"
        token_secret_key: "token"
      ref: "main" 
      path_in_repo: "/datasets" 
      resource_types: ["dataset"] 
      scan_interval_seconds: 300

    - name: "pipelines"
      url: "https://github.com/mlpie-hq/tests"
      auth:
        type: "token"
        secret_ref: "test-repo"
        token_secret_key: "token"
      ref: "main"
      path_in_repo: "/pipelines"
      resource_types: ["pipeline"] 
